language: node_js
sudo: required
before_install:
  - npm install -g node-gyp
node_js:
- stable
notifications:
  slack:
    secure: Z0gAdQDMF93T982MhcUT5svqBTzVX/c2vyzpeNQed/n8q1j7IJEos9VSTEDQ5a4m9K1dTBbt8z+xhM57ZqcfJQ3uI/M+F2daCk7KUojmtc9Nc1Vwi2zvarSTNh+pH3i6KrEKocA7OLJ7TJz873yPbptfq/s9KHCyI2Y6e2v/IPtNkAIIlgNqGHk2flbEb1WUmsenoA84DMGAU869z3GNvwPPSG8XquwiUH/FQQE6v1GJGphNzPzZwhTX/pdQmIO9NKknYFJSXhEne/tgOtk9xJt0DXAK24AL9My77ZzaP6LQrsCnzoiwo//DX5KTiIncPyrFxGG7aWWh9xQ09GhJFV+D6HIxcohDKrWjs/KptQql3gbK84D3Keo2jTnDv88wILJdkYqt3SYmlw8Uf14o/ND8oFdDBk7nrN2oRASH8YEmGFeCe1+GVQNw0TkcTmwqu9OLklh56OC0eKAq38hNeN67PCCUHrP2nVTeOAl6Ql4FUVPOtudye7ycfVT6YW5D2Y9A6hm+fHJLaPoG94RPQGEBsAvDfb2RkeDFhcwdVaebfWWDLm0n43feiOlQ4acfCnJxa8ND6Nq9BGG2r/4D/4K+wnpoNsEl9P9ZCUJs9eTv/oGMftXAPbqTYynJJWfvvHXR2gJUAmCQbQowNtcPkDtdN/zP1khQkr89q3Za/D0=
  email: false
env:
  - CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5